

INSERT INTO `countries` (`id`, `code`, `name`, `phonecode`,`flag`) VALUES
(1, 'AF', 'Afghanistan', 93, '/flags/flag-of-Afghanistan.jpg'),
(2, 'AL', 'Albania', 355, '/flags/flag-of-Albania.jpg'),
(3, 'DZ', 'Algeria', 213, '/flags/flag-of-Algeria.jpg'),
(4, 'AS', 'American Samoa', 1684, null),
(5, 'AD', 'Andorra', 376, '/flags/flag-of-Andorra.jpg'),
(6, 'AO', 'Angola', 244, '/flags/flag-of-Angola.jpg'),
(7, 'AI', 'Anguilla', 1264, null),
(8, 'AQ', 'Antarctica', 0, null),
(9, 'AG', 'Antigua And Barbuda', 1268, '/flags/flag-of-Antigua.jpg'),
(10, 'AR', 'Argentina', 54, '/flags/flag-of-Argentina.jpg'),
(11, 'AM', 'Armenia', 374, '/flags/flag-of-Armenia.jpg'),
(12, 'AW', 'Aruba', 297, null),
(13, 'AU', 'Australia', 61, '/flags/flag-of-Australia.jpg'),
(14, 'AT', 'Austria', 43, '/flags/flag-of-Austria.jpg'),
(15, 'AZ', 'Azerbaijan', 994, '/flags/flag-of-Azerbaijan.jpg'),
(16, 'BS', 'Bahamas The', 1242, '/flags/flag-of-Bahamas.jpg'),
(17, 'BH', 'Bahrain', 973, '/flags/flag-of-Bahrain.jpg'),
(18, 'BD', 'Bangladesh', 880, '/flags/flag-of-Bangladesh.jpg'),
(19, 'BB', 'Barbados', 1246, '/flags/flag-of-Barbados.jpg'),
(20, 'BY', 'Belarus', 375, '/flags/flag-of-Belarus.jpg'),
(21, 'BE', 'Belgium', 32, '/flags/flag-of-Belgium.jpg'),
(22, 'BZ', 'Belize', 501, '/flags/flag-of-Belize.jpg'),
(23, 'BJ', 'Benin', 229, '/flags/flag-of-Benin.jpg'),
(24, 'BM', 'Bermuda', 1441, null),
(25, 'BT', 'Bhutan', 975, '/flags/flag-of-Bhutan.jpg'),
(26, 'BO', 'Bolivia', 591, '/flags/flag-of-Bolivia.jpg'),
(27, 'BA', 'Bosnia and Herzegovina', 387, '/flags/flag-of-Bosnia-Herzegovina.jpg'),
(28, 'BW', 'Botswana', 267, '/flags/flag-of-Botswana.jpg'),
(29, 'BV', 'Bouvet Island', 0, null),
(30, 'BR', 'Brazil', 55, '/flags/flag-of-Brazil.jpg'),
(31, 'IO', 'British Indian Ocean Territory', 246, null),
(32, 'BN', 'Brunei', 673, '/flags/flag-of-Brunei.jpg'),
(33, 'BG', 'Bulgaria', 359, '/flags/flag-of-Bulgaria.jpg'),
(34, 'BF', 'Burkina Faso', 226, '/flags/flag-of-Burkina-Faso.jpg'),
(35, 'BI', 'Burundi', 257, '/flags/flag-of-Burundi.jpg'),
(36, 'KH', 'Cambodia', 855, '/flags/flag-of-Cambodia.jpg'),
(37, 'CM', 'Cameroon', 237, '/flags/flag-of-Cameroon.jpg'),
(38, 'CA', 'Canada', 1, '/flags/flag-of-Canada.jpg'),
(39, 'CV', 'Cape Verde', 238, '/flags/flag-of-Cabo-Verde.jpg'),
(40, 'KY', 'Cayman Islands', 1345, null),
(41, 'CF', 'Central African Republic', 236, '/flags/flag-of-Central-African-Republic.jpg'),
(42, 'TD', 'Chad', 235, '/flags/flag-of-Chad.jpg'),
(43, 'CL', 'Chile', 56, '/flags/flag-of-Chile.jpg'),
(44, 'CN', 'China', 86, '/flags/flag-of-China.jpg'),
(45, 'CX', 'Christmas Island', 61, null),
(46, 'CC', 'Cocos (Keeling) Islands', 672, null),
(47, 'CO', 'Colombia', 57, '/flags/flag-of-Colombia.jpg'),
(48, 'KM', 'Comoros', 269, '/flags/flag-of-Comoros.jpg'),
(49, 'CG', 'Republic Of The Congo', 242, '/flags/flag-of-Congo.jpg'),
(50, 'CD', 'Democratic Republic Of The Congo', 242, '/flags/flag-of-Congo-Democratic-Republic-of.jpg'),
(51, 'CK', 'Cook Islands', 682, null),
(52, 'CR', 'Costa Rica', 506, '/flags/flag-of-Costa-Rica.jpg'),
(53, 'CI', 'Cote D''Ivoire (Ivory Coast)', 225, '/flags/flag-of-Cote-d-Ivoire.jpg'),
(54, 'HR', 'Croatia (Hrvatska)', 385, '/flags/flag-of-Croatia.jpg'),
(55, 'CU', 'Cuba', 53, '/flags/flag-of-Cuba.jpg'),
(56, 'CY', 'Cyprus', 357, '/flags/flag-of-Cyprus.jpg'),
(57, 'CZ', 'Czech Republic', 420, '/flags/flag-of-Czech-Republic.jpg'),
(58, 'DK', 'Denmark', 45, '/flags/flag-of-Denmark.jpg'),
(59, 'DJ', 'Djibouti', 253, '/flags/flag-of-Djibouti.jpg'),
(60, 'DM', 'Dominica', 1767, '/flags/flag-of-Dominica.jpg'),
(61, 'DO', 'Dominican Republic', 1809, '/flags/flag-of-Dominican-Republic.jpg'),
(62, 'TP', 'East Timor', 670, null),
(63, 'EC', 'Ecuador', 593, '/flags/flag-of-Ecuador.jpg'),
(64, 'EG', 'Egypt', 20, '/flags/flag-of-Egypt.jpg'),
(65, 'SV', 'El Salvador', 503, '/flags/flag-of-El-Salvador.jpg'),
(66, 'GQ', 'Equatorial Guinea', 240, '/flags/flag-of-Equatorial-Guinea.jpg'),
(67, 'ER', 'Eritrea', 291, '/flags/flag-of-Eritrea.jpg'),
(68, 'EE', 'Estonia', 372, '/flags/flag-of-Estonia.jpg'),
(69, 'ET', 'Ethiopia', 251, '/flags/flag-of-Ethiopia.jpg'),
(70, 'XA', 'External Territories of Australia', 61, null),
(71, 'FK', 'Falkland Islands', 500, null),
(72, 'FO', 'Faroe Islands', 298, null),
(73, 'FJ', 'Fiji Islands', 679, '/flags/flag-of-Fiji.jpg'),
(74, 'FI', 'Finland', 358, '/flags/flag-of-Finland.jpg'),
(75, 'FR', 'France', 33, '/flags/flag-of-France.jpg'),
(76, 'GF', 'French Guiana', 594, null),
(77, 'PF', 'French Polynesia', 689, null),
(78, 'TF', 'French Southern Territories', 0, null),
(79, 'GA', 'Gabon', 241, '/flags/flag-of-Gabon.jpg'),
(80, 'GM', 'Gambia The', 220, '/flags/flag-of-Gambia.jpg'),
(81, 'GE', 'Georgia', 995, '/flags/flag-of-Georgia.jpg'),
(82, 'DE', 'Germany', 49, '/flags/flag-of-Germany.jpg'),
(83, 'GH', 'Ghana', 233, '/flags/flag-of-Ghana.jpg'),
(84, 'GI', 'Gibraltar', 350, null),
(85, 'GR', 'Greece', 30, '/flags/flag-of-Greece.jpg'),
(86, 'GL', 'Greenland', 299, null),
(87, 'GD', 'Grenada', 1473, '/flags/flag-of-Grenada.jpg'),
(88, 'GP', 'Guadeloupe', 590, null),
(89, 'GU', 'Guam', 1671, null),
(90, 'GT', 'Guatemala', 502, '/flags/flag-of-Guatemala.jpg'),
(91, 'XU', 'Guernsey and Alderney', 44, null),
(92, 'GN', 'Guinea', 224, '/flags/flag-of-Guinea.jpg'),
(93, 'GW', 'Guinea-Bissau', 245, '/flags/flag-of-Guinea-Bissau.jpg'),
(94, 'GY', 'Guyana', 592, '/flags/flag-of-Guyana.jpg'),
(95, 'HT', 'Haiti', 509, '/flags/flag-of-Haiti.jpg'),
(96, 'HM', 'Heard and McDonald Islands', 0, null),
(97, 'HN', 'Honduras', 504, '/flags/flag-of-Honduras.jpg'),
(98, 'HK', 'Hong Kong S.A.R.', 852, null),
(99, 'HU', 'Hungary', 36, '/flags/flag-of-Hungary.jpg'),
(100, 'IS', 'Iceland', 354, '/flags/flag-of-Iceland.jpg'),
(101, 'IN', 'India', 91, '/flags/flag-of-India.jpg'),
(102, 'ID', 'Indonesia', 62, '/flags/flag-of-Indonesia.jpg'),
(103, 'IR', 'Iran', 98, '/flags/flag-of-Iran.jpg'),
(104, 'IQ', 'Iraq', 964, '/flags/flag-of-Iraq.jpg'),
(105, 'IE', 'Ireland', 353, '/flags/flag-of-Ireland.jpg'),
(106, 'IL', 'Israel', 972, '/flags/flag-of-Israel.jpg'),
(107, 'IT', 'Italy', 39, '/flags/flag-of-Italy.jpg'),
(108, 'JM', 'Jamaica', 1876, '/flags/flag-of-Jamaica.jpg'),
(109, 'JP', 'Japan', 81, '/flags/flag-of-Japan.jpg'),
(110, 'XJ', 'Jersey', 44, null),
(111, 'JO', 'Jordan', 962, '/flags/flag-of-Jordan.jpg'),
(112, 'KZ', 'Kazakhstan', 7, '/flags/flag-of-Kazakhstan.jpg'),
(113, 'KE', 'Kenya', 254, '/flags/flag-of-Kenya.jpg'),
(114, 'KI', 'Kiribati', 686, '/flags/flag-of-Kiribati.jpg'),
(115, 'KP', 'Korea North', 850, '/flags/flag-of-Korea-North.jpg'),
(116, 'KR', 'Korea South', 82, '/flags/flag-of-Korea-South.jpg'),
(117, 'KW', 'Kuwait', 965, '/flags/flag-of-Kuwait.jpg'),
(118, 'KG', 'Kyrgyzstan', 996, '/flags/flag-of-Kyrgyzstan.jpg'),
(119, 'LA', 'Laos', 856, '/flags/flag-of-Laos.jpg'),
(120, 'LV', 'Latvia', 371, '/flags/flag-of-Latvia.jpg'),
(121, 'LB', 'Lebanon', 961, '/flags/flag-of-Lebanon.jpg'),
(122, 'LS', 'Lesotho', 266, '/flags/flag-of-Lesotho.jpg'),
(123, 'LR', 'Liberia', 231, '/flags/flag-of-Liberia.jpg'),
(124, 'LY', 'Libya', 218, '/flags/flag-of-Libya.jpg'),
(125, 'LI', 'Liechtenstein', 423, '/flags/flag-of-Liechtenstein.jpg'),
(126, 'LT', 'Lithuania', 370, '/flags/flag-of-Lithuania.jpg'),
(127, 'LU', 'Luxembourg', 352, '/flags/flag-of-Luxembourg.jpg'),
(128, 'MO', 'Macau S.A.R.', 853, null),
(129, 'MK', 'Macedonia', 389, '/flags/flag-of-Macedonia.jpg'),
(130, 'MG', 'Madagascar', 261, '/flags/flag-of-Madagascar.jpg'),
(131, 'MW', 'Malawi', 265, '/flags/flag-of-Malawi.jpg'),
(132, 'MY', 'Malaysia', 60, '/flags/flag-of-Malaysia.jpg'),
(133, 'MV', 'Maldives', 960, '/flags/flag-of-Maldives.jpg'),
(134, 'ML', 'Mali', 223, '/flags/flag-of-Mali.jpg'),
(135, 'MT', 'Malta', 356, '/flags/flag-of-Malta.jpg'),
(136, 'XM', 'Man (Isle of)', 44, null),
(137, 'MH', 'Marshall Islands', 692, '/flags/flag-of-Marshall-Islands.jpg'),
(138, 'MQ', 'Martinique', 596, null),
(139, 'MR', 'Mauritania', 222, '/flags/flag-of-Mauritania.jpg'),
(140, 'MU', 'Mauritius', 230, '/flags/flag-of-Mauritius.jpg'),
(141, 'YT', 'Mayotte', 269, null),
(142, 'MX', 'Mexico', 52, '/flags/flag-of-Mexico.jpg'),
(143, 'FM', 'Micronesia', 691, '/flags/flag-of-Micronesia.jpg'),
(144, 'MD', 'Moldova', 373, '/flags/flag-of-Moldova.jpg'),
(145, 'MC', 'Monaco', 377, '/flags/flag-of-Monaco.jpg'),
(146, 'MN', 'Mongolia', 976, '/flags/flag-of-Mongolia.jpg'),
(147, 'MS', 'Montserrat', 1664, null),
(148, 'MA', 'Morocco', 212, '/flags/flag-of-Morocco.jpg'),
(149, 'MZ', 'Mozambique', 258, '/flags/flag-of-Mozambique.jpg'),
(150, 'MM', 'Myanmar', 95, '/flags/flag-of-Myanmar.jpg'),
(151, 'NA', 'Namibia', 264, '/flags/flag-of-Namibia.jpg'),
(152, 'NR', 'Nauru', 674, '/flags/flag-of-Nauru.jpg'),
(153, 'NP', 'Nepal', 977, '/flags/flag-of-Nepal.jpg'),
(154, 'AN', 'Netherlands Antilles', 599, '/flags/flag-of-Netherlands.jpg'),
(155, 'NL', 'Netherlands The', 31, '/flags/flag-of-Netherlands.jpg'),
(156, 'NC', 'New Caledonia', 687, null),
(157, 'NZ', 'New Zealand', 64, '/flags/flag-of-New-Zealand.jpg'),
(158, 'NI', 'Nicaragua', 505, '/flags/flag-of-Nicaragua.jpg'),
(159, 'NE', 'Niger', 227, '/flags/flag-of-Niger.jpg'),
(160, 'NG', 'Nigeria', 234, '/flags/flag-of-Nigeria.jpg'),
(161, 'NU', 'Niue', 683, null),
(162, 'NF', 'Norfolk Island', 672, null),
(163, 'MP', 'Northern Mariana Islands', 1670, null),
(164, 'NO', 'Norway', 47, '/flags/flag-of-Norway.jpg'),
(165, 'OM', 'Oman', 968, '/flags/flag-of-Oman.jpg'),
(166, 'PK', 'Pakistan', 92, '/flags/flag-of-Pakistan.jpg'),
(167, 'PW', 'Palau', 680, '/flags/flag-of-Palau.jpg'),
(168, 'PS', 'Palestinian Territory Occupied', 970, '/flags/flag-of-Palestine.jpg'),
(169, 'PA', 'Panama', 507, '/flags/flag-of-Panama.jpg'),
(170, 'PG', 'Papua new Guinea', 675, '/flags/flag-of-Papua-New-Guinea.jpg'),
(171, 'PY', 'Paraguay', 595, '/flags/flag-of-Paraguay.jpg'),
(172, 'PE', 'Peru', 51, '/flags/flag-of-Peru.jpg'),
(173, 'PH', 'Philippines', 63, '/flags/flag-of-Philippines.jpg'),
(174, 'PN', 'Pitcairn Island', 0, null),
(175, 'PL', 'Poland', 48, '/flags/flag-of-Poland.jpg'),
(176, 'PT', 'Portugal', 351, '/flags/flag-of-Portugal.jpg'),
(177, 'PR', 'Puerto Rico', 1787, null),
(178, 'QA', 'Qatar', 974, '/flags/flag-of-Qatar.jpg'),
(179, 'RE', 'Reunion', 262, null),
(180, 'RO', 'Romania', 40, '/flags/flag-of-Romania.jpg'),
(181, 'RU', 'Russia', 70, '/flags/flag-of-Russia.jpg'),
(182, 'RW', 'Rwanda', 250, '/flags/flag-of-Rwanda.jpg'),
(183, 'SH', 'Saint Helena', 290, null),
(184, 'KN', 'Saint Kitts And Nevis', 1869, null),
(185, 'LC', 'Saint Lucia', 1758, null),
(186, 'PM', 'Saint Pierre and Miquelon', 508, null),
(187, 'VC', 'Saint Vincent And The Grenadines', 1784, null),
(188, 'WS', 'Samoa', 684, '/flags/flag-of-Samoa.jpg'),
(189, 'SM', 'San Marino', 378, '/flags/flag-of-San-Marino.jpg'),
(190, 'ST', 'Sao Tome and Principe', 239, '/flags/flag-of-Sao-Tome-and-Principe.jpg'),
(191, 'SA', 'Saudi Arabia', 966, '/flags/flag-of-Saudi-Arabia.jpg'),
(192, 'SN', 'Senegal', 221, '/flags/flag-of-Senegal.jpg'),
(193, 'RS', 'Serbia', 381, '/flags/flag-of-Serbia.jpg'),
(194, 'SC', 'Seychelles', 248, '/flags/flag-of-Seychelles.jpg'),
(195, 'SL', 'Sierra Leone', 232, '/flags/flag-of-Sierra-Leone.jpg'),
(196, 'SG', 'Singapore', 65, '/flags/flag-of-Singapore.jpg'),
(197, 'SK', 'Slovakia', 421, '/flags/flag-of-Slovakia.jpg'),
(198, 'SI', 'Slovenia', 386, '/flags/flag-of-Slovenia.jpg'),
(199, 'XG', 'Smaller Territories of the UK', 44, null),
(200, 'SB', 'Solomon Islands', 677, '/flags/flag-of-Solomon-Islands.jpg'),
(201, 'SO', 'Somalia', 252, '/flags/flag-of-Somalia.jpg'),
(202, 'ZA', 'South Africa', 27, '/flags/flag-of-South-Africa.jpg'),
(203, 'GS', 'South Georgia', 0, null),
(204, 'SS', 'South Sudan', 211, '/flags/flag-of-South-Sudan.jpg'),
(205, 'ES', 'Spain', 34, '/flags/flag-of-Spain.jpg'),
(206, 'LK', 'Sri Lanka', 94, '/flags/flag-of-Sri-Lanka.jpg'),
(207, 'SD', 'Sudan', 249, '/flags/flag-of-Sudan.jpg'),
(208, 'SR', 'Suriname', 597, '/flags/flag-of-Suriname.jpg'),
(209, 'SJ', 'Svalbard And Jan Mayen Islands', 47, null),
(210, 'SZ', 'Swaziland', 268, '/flags/flag-of-Swaziland.jpg'),
(211, 'SE', 'Sweden', 46, '/flags/flag-of-Sweden.jpg'),
(212, 'CH', 'Switzerland', 41, '/flags/flag-of-Switzerland.jpg'),
(213, 'SY', 'Syria', 963, '/flags/flag-of-Syria.jpg'),
(214, 'TW', 'Taiwan', 886, '/flags/flag-of-Taiwan.jpg'),
(215, 'TJ', 'Tajikistan', 992, '/flags/flag-of-Tajikistan.jpg'),
(216, 'TZ', 'Tanzania', 255, '/flags/flag-of-Tanzania.jpg'),
(217, 'TH', 'Thailand', 66, '/flags/flag-of-Thailand.jpg'),
(218, 'TG', 'Togo', 228, '/flags/flag-of-Togo.jpg'),
(219, 'TK', 'Tokelau', 690, null),
(220, 'TO', 'Tonga', 676, '/flags/flag-of-Tonga.jpg'),
(221, 'TT', 'Trinidad And Tobago', 1868, '/flags/flag-of-Trinidad-and-Tobago.jpg'),
(222, 'TN', 'Tunisia', 216, '/flags/flag-of-Tunisia.jpg'),
(223, 'TR', 'Turkey', 90, '/flags/flag-of-Turkey.jpg'),
(224, 'TM', 'Turkmenistan', 7370, '/flags/flag-of-Turkmenistan.jpg'),
(225, 'TC', 'Turks And Caicos Islands', 1649, null),
(226, 'TV', 'Tuvalu', 688, '/flags/flag-of-Tuvalu.jpg'),
(227, 'UG', 'Uganda', 256, '/flags/flag-of-Uganda.jpg'),
(228, 'UA', 'Ukraine', 380, '/flags/flag-of-Ukraine.jpg'),
(229, 'AE', 'United Arab Emirates', 971, '/flags/flag-of-United-Arab-Emirates.jpg'),
(230, 'GB', 'United Kingdom', 44, '/flags/flag-of-United-Kingdom.jpg'),
(231, 'US', 'United States', 1, '/flags/flag-of-United-States-of-America.jpg'),
(232, 'UM', 'United States Minor Outlying Islands', 1, null),
(233, 'UY', 'Uruguay', 598, '/flags/flag-of-Uruguay.jpg'),
(234, 'UZ', 'Uzbekistan', 998, '/flags/flag-of-Uzbekistan.jpg'),
(235, 'VU', 'Vanuatu', 678, '/flags/flag-of-Vanuatu.jpg'),
(236, 'VA', 'Vatican City State (Holy See)', 39, '/flags/flag-of-Vatican-City.jpg'),
(237, 'VE', 'Venezuela', 58, '/flags/flag-of-Venezuela.jpg'),
(238, 'VN', 'Vietnam', 84, '/flags/flag-of-Vietnam.jpg'),
(239, 'VG', 'Virgin Islands (British)', 1284, null),
(240, 'VI', 'Virgin Islands (US)', 1340, null),
(241, 'WF', 'Wallis And Futuna Islands', 681, null),
(242, 'EH', 'Western Sahara', 212, null),
(243, 'YE', 'Yemen', 967, '/flags/flag-of-Yemen.jpg'),
(244, 'YU', 'Yugoslavia', 38, null),
(245, 'ZM', 'Zambia', 260, '/flags/flag-of-Zambia.jpg'),
(246, 'ZW', 'Zimbabwe', 263, '/flags/flag-of-Zimbabwe.jpg');



