INSERT INTO `dynamic_pages` (`id`, `title`, `slug`, `description`, `status`, `is_static`,`created_at`,`updated_at`) VALUES
(1, 'About Us', 'about-us', 'initial description', 1, 1, NOW(), NOW()),
(3, 'Blog', 'blog', 'initial description', 1, 1, NOW(), NOW()),
(4, 'Become A Merchant', 'merchant', 'initial description', 1, 1, NOW(), NOW()),
(5, 'My Account', 'profile', 'initial description', 1, 1, NOW(), NOW()),
(6, 'My Orders', 'my-purchase-orders', 'initial description', 1, 1, NOW(), NOW()),
(7, 'My Cart', 'cart', 'initial description', 1, 1, NOW(), NOW()),
(8, 'My Wish List', 'my-wishlist', 'initial description', 1, 1, NOW(), NOW()),
(9, 'Refunds & Disputes', 'refund/my-refund-list', 'initial description', 1, 1, NOW(), NOW()),
(10, 'My Coupons', 'profile/coupons', 'initial description', 1, 1, NOW(), NOW()),
(11, 'My Wallet', 'wallet/customer/my-wallet-index', 'initial description', 1, 1, NOW(), NOW()),
(12, 'Referral', 'profile/referral', 'initial description', 1, 1, NOW(), NOW()),
(13, 'Help & Contact Us', 'contact-us', 'initial description', 1, 1, NOW(), NOW()),
(14, 'Track Orders', 'track-order', 'initial description', 1, 1, NOW(), NOW()),
(15, 'Support Tickets', 'support-ticket', 'initial description', 1, 1, NOW(), NOW()),
(16, 'Compare', 'compare', 'initial description', 1, 1, NOW(), NOW()),
(17, 'Dashboard', 'profile/dashboard', 'initial description', 1, 1, NOW(), NOW()),
(18, 'Shopping Recent Viewed', 'shopping-recent-viewed', 'initial description', 1, 1, NOW(), NOW()),
(19, 'My Giftcarts', 'purchased-gift-cards', 'initial description', 1, 1, NOW(), NOW()),
(20, 'My Digital Products', 'digital-products', 'initial description', 1, 1, NOW(), NOW()),
(21, 'Return & Exchange', 'return-exchange', 'initial description', 1, 1, NOW(), NOW());
